# Recommended R Libraries
# 0. All In One Cammand Wrap-Up
# from https://www.r-bloggers.com/2020/04/essential-list-of-useful-r-packages-for-data-scientists/

# List of recommended packages
AllPackages <- c("Hmisc","foreign","protr","readxl", "readODS", 
                 "csv","readr","tidyverse","jsonlite","rjson",
                 "RJSONIO","jsonvalidate","sparkavro","arrow","feather",
                 "XML","odbc","RODBC","mssqlR","RMySQL",
                 "postGIStools","RPostgreSQL","odbc", "remotes",
                 "RSQLite","sqliter","dbflobr","RSQL","sqldf",
                 "queryparser","influxdbr","janitor","outliers",
                 "missForest","frequency","Amelia","diffobj","mice", "VIM",
                 "mi","wrangle","mitools",
                 "stringr","lubridate","glue","scales","hablar",
                 "dplyr","magrittr","data.table","plyr",
                 "tidyr","tibble","reshape2","stats","lars",
                 "caret","survival","gam","glmnet","quantreg",
                 "sgd","BLR","MASS","car","mlogit","RRedshiftSQL",
                 "earth","faraway","nortest","lmtest","nlme",
                 "splines","sem","pls","tree","rpart","rio",
                 "FuzzyNumbers","ez","psych","pastecs","CCA","CCP",
                 "icapca","gvlma","smacof","MVN","rpca",
                 "EFA.MRFA","MFAg","MVar","fabMix", "fad","spBFA","mnlfa",
                 "GFA","lmds","SPCALDA","semds","superMDS",
                 "vcd","vcdExtra","ks","rrcov","eRm",
                 "MNP","bayesm","ltm","fpc","cluster",
                 "treeClust","e1071","NbClust","skmeans","kml",
                 "compHclust","protoclust","pvclust","genie","tclust",
                 "ClusterR","dbscan","CEC","GMCM","EMCluster",
                 "randomLCA","MOCCA","factoextra","poLCA",
                 "zoo","xts","timeSeries","tsModel","TSMining",
                 "TSA","fma","fpp2","fpp3","tsfa",
                 "TSdist","TSclust","feasts","MTS","dse",
                 "sazedR","kza","fable","forecast","tseries",
                 "nnfor","quantmod","fastnet","tsna","sna",
                 "networkR","InteractiveIGraph","SemNeT","igraph",
                 "dyads","staTools","CINNA","tm","tau","NetworkToolbox",
                 "koRpus","lexicon","sylly","textir","textmineR",
                 "MediaNews","lsa","ngram","ngramrr","corpustools",
                 "udpipe","textstem","tidytext","text2vec","crossval",
                 "klaR","gencve","cvAUC",
                 "CVThresh","cvTools","dcv","cvms","blockCV",
                 "randomForest","grf","ipred","party","randomForestSRC",
                 "BART","Boruta","LTRCtrees","REEMtree",
                 "binomialRF","superml","gbm",
                 "GMMBoost","bst","sboost","C50",
                 "kernlab","svmpath","nnet","gnn","rnn",
                 "spnn","brnn","RSNNS","AMORE","simpleNeural",
                 "ANN2","yap","yager","deep","neuralnet",
                 "TeachNet","deepnet","RcppDL","tensorflow","h2o",
                 "kerasR","deepNN","Buddle","automl","RLT",
                 "ReinforcementLearning","MDPtoolbox","lime","localModel",
                 "iml","flashlight","interpret","outliertree",
                 "dockerfiler", "sparklyr","cloudml","ggvis",
                 "htmlwidgets","maps","sunburstR","lattice","predict3d",
                 "rgl","rglwidget","plot3Drgl","ggmap","ggplot2",
                 "plotly","RColorBrewer","dygraphs","canvasXpress","qgraph",
                 "moveVis","ggcharts","visNetwork","visreg","sjPlot",
                 "squash","mlr3viz","DiagrammeR",
                 "pavo","rasterVis","timelineR","DataViz","d3r","breakDown",
                 "dashboard","highcharter","rbokeh","rvest",
                 "Rcrawler","ralger","scrapeR","devtools","usethis",
                 "roxygen2","knitr","rmarkdown","flexdashboard","shiny",
                 "xtable","httr","profvis", "installr")
# create list of missing packages
new.packages <- AllPackages[!(AllPackages %in% installed.packages()[,"Package"])]
# install missing packages
if(length(new.packages)) install.packages(new.packages)
# load all recommended packages
lapply(AllPackages, library, character.only = TRUE)  
